In [1]:
import torch

In [2]:
x = torch.tensor([[1,2,3],[4,5,6]])
print(x)

tensor([[1, 2, 3],
        [4, 5, 6]])


In [4]:
print(x.view(3, 2)) # this is view -> whatever is most convinient

tensor([[1, 2],
        [3, 4],
        [5, 6]])


In [5]:
print(x.permute(1,0)) # this is transpose

tensor([[1, 4],
        [2, 5],
        [3, 6]])
